framework:
#    messenger:
#
#        transports:
#            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
#
#        routing:
#            'Aa\AkeneoImport\ImportCommand\CommandListInterface': amqp

#        serializer:
#            context:
#                skip_null_values: true

# Default middleware handlers
# Symfony\Component\Messenger\Middleware\LoggingMiddleware
# Symfony\Component\Messenger\Middleware\SendMessageMiddleware
# Symfony\Component\Messenger\Middleware\HandleMessageMiddleware


