framework:
    messenger:

        transports:
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

#        routing:
#            'App\MyMessage': amqp

#        serializer:
#            format: json_patch




