framework:
    messenger:

        transports:
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

#        routing:
#            'App\MyMessage': amqp

#        serializer:
#            format: json_patch

# Default middleware handlers
# Symfony\Component\Messenger\Middleware\LoggingMiddleware
# Symfony\Component\Messenger\Middleware\SendMessageMiddleware
# Symfony\Component\Messenger\Middleware\HandleMessageMiddleware


