services:

    ### Debug
#    Aa\AkeneoImport\MessageHandler\CommandListMessageHandler:
#        arguments:
#            - '@Aa\AkeneoImport\CommandHandler\ApiBatchHandler'
#        tags:
#            - messenger.message_handler
#

    ### API batch handler

    Aa\AkeneoImport\CommandHandler\ApiBatchHandler:
        arguments:
            - '@aa.api.client'
            - '@serializer'

    aa.api.client_builder:
        class: Akeneo\Pim\ApiClient\AkeneoPimClientBuilder
        arguments:
            - '%env(AKENEO_API_HOST)%'

    aa.api.client:
        class: Akeneo\Pim\ApiClient\AkeneoPimClientInterface
        factory: 'aa.api.client_builder:buildAuthenticatedByPassword'
        arguments:
            - '%env(AKENEO_API_CLIENT_ID)%'
            - '%env(AKENEO_API_SECRET)%'
            - '%env(AKENEO_API_USER)%'
            - '%env(AKENEO_API_PASSWORD)%'

    Akeneo\Pim\ApiClient\AkeneoPimClientInterface: '@aa.api.client'


    ## Serializer

    Aa\AkeneoImport\Serializer\CommandListNormalizer:
        calls:
            - ['setDenormalizer', ['@serializer']]
            - ['setNormalizer', ['@serializer']]
        tags:
            - { name: 'serializer.normalizer' }

    Aa\AkeneoImport\Serializer\CommandNormalizer:
        calls:
            - ['setNormalizer', ['@serializer']]
        tags:
            - { name: 'serializer.normalizer' }


    ## App

    Aa\AkeneoImport\CommandBus\Transport\TransportFactory:
        arguments:
          - '%env(ENQUEUE_DSN)%'

    Aa\AkeneoImport\CommandBus\Transport\Sender:
        factory: 'Aa\AkeneoImport\CommandBus\Transport\TransportFactory:createSender'

    Aa\AkeneoImport\CommandBus\Transport\Receiver:
        factory: 'Aa\AkeneoImport\CommandBus\Transport\TransportFactory:createReceiver'


    Aa\AkeneoImport\CommandHandler\AsyncCommandListHandler:
        arguments:
          - '@Aa\AkeneoImport\CommandBus\Transport\Sender'

    Aa\AkeneoImport\CommandBus\CommandBusFactory:

    Aa\AkeneoImport\Import\Importer:
        arguments:
            - '@Aa\AkeneoImport\CommandBus\CommandBusFactory'

    Aa\AkeneoImport\CommandBus\Consumer:
        arguments:
            - '@Aa\AkeneoImport\CommandBus\Transport\Receiver'


    App\Command\ImportCommand:
        arguments:
            - '@Aa\AkeneoImport\Import\Importer'
            - '@App\PoC\TestProvider'
            -
                api: '@Aa\AkeneoImport\CommandHandler\ApiBatchHandler'
                amqp: '@Aa\AkeneoImport\CommandHandler\AsyncCommandListHandler'
        tags: ['console.command']

    App\Command\ConsumeCommand:
        arguments:
            - '@Aa\AkeneoImport\CommandBus\Consumer'
            -
                api: '@Aa\AkeneoImport\CommandHandler\ApiBatchHandler'
        tags: ['console.command']
