services:


    ### API batch handler

    Aa\AkeneoImport\CommandHandler\ApiBatchHandlerFactory:
        arguments:
            - '@aa.api.client'

    Aa\AkeneoImport\CommandHandler\ApiBatchHandler:
        factory: 'Aa\AkeneoImport\CommandHandler\ApiBatchHandlerFactory:createHandler'

    aa.api.client_builder:
        class: Akeneo\Pim\ApiClient\AkeneoPimClientBuilder
        arguments:
            - '%env(AKENEO_API_HOST)%'

    aa.api.client:
        class: Akeneo\Pim\ApiClient\AkeneoPimClientInterface
        factory: 'aa.api.client_builder:buildAuthenticatedByPassword'
        arguments:
            - '%env(AKENEO_API_CLIENT_ID)%'
            - '%env(AKENEO_API_SECRET)%'
            - '%env(AKENEO_API_USER)%'
            - '%env(AKENEO_API_PASSWORD)%'

    ## Akeneo Import

    Aa\AkeneoImport\CommandBus\Transport\TransportFactory:
        arguments:
          - '%env(ENQUEUE_DSN)%'

    Aa\AkeneoImport\CommandBus\Transport\Sender:
        factory: 'Aa\AkeneoImport\CommandBus\Transport\TransportFactory:createSender'

    Aa\AkeneoImport\CommandBus\Transport\Receiver:
        factory: 'Aa\AkeneoImport\CommandBus\Transport\TransportFactory:createReceiver'

    Aa\AkeneoImport\CommandHandler\AsyncCommandListHandler:
        arguments:
          - '@Aa\AkeneoImport\CommandBus\Transport\Sender'

    Aa\AkeneoImport\CommandBus\CommandBusFactory:

    Aa\AkeneoImport\Import\Importer:
        arguments:
            - '@Aa\AkeneoImport\CommandBus\CommandBusFactory'

    Aa\AkeneoImport\CommandBus\Consumer:
        arguments:
            - '@Aa\AkeneoImport\CommandBus\Transport\Receiver'

    ## App

    App\Command\ImportCommand:
        arguments:
            - '@Aa\AkeneoImport\Import\Importer'
            -
                product: '@App\Example\TestProductProvider'
                model: '@App\Example\TestProductAndModelProvider'
                media: '@App\Example\ProductWithMediaProvider'
            -
                api: '@Aa\AkeneoImport\CommandHandler\ApiBatchHandler'
                amqp: '@Aa\AkeneoImport\CommandHandler\AsyncCommandListHandler'
        tags: ['console.command']

    App\Command\ConsumeCommand:
        arguments:
            - '@Aa\AkeneoImport\CommandBus\Consumer'
            -
                api: '@Aa\AkeneoImport\CommandHandler\ApiBatchHandler'
            -
                product: 'Aa\AkeneoImport\ImportCommand\Product\UpdateOrCreateProduct'
                model: 'Aa\AkeneoImport\ImportCommand\ProductModel\UpdateOrCreateProductModel'
        tags: ['console.command']
