services:

    Akeneo\Pim\ApiClient\AkeneoPimClientBuilder:
        arguments:
            - '%env(AKENEO_API_HOST)%'

    Akeneo\Pim\ApiClient\AkeneoPimClient:
        factory: 'Akeneo\Pim\ApiClient\AkeneoPimClientBuilder:buildAuthenticatedByPassword'
        arguments:
            - '%env(AKENEO_API_CLIENT_ID)%'
            - '%env(AKENEO_API_SECRET)%'
            - '%env(AKENEO_API_USER)%'
            - '%env(AKENEO_API_PASSWORD)%'

    ## Akeneo Import

    Aa\AkeneoImport\Import\ApiImporterFactory:

    Aa\AkeneoImport\Import\Importer:
        factory: 'Aa\AkeneoImport\Import\ApiImporterFactory:createByApiClient'
        arguments:
            - '@Akeneo\Pim\ApiClient\AkeneoPimClient'

    Aa\AkeneoImport\Queue\RemoteQueueFactory:
        arguments:
          - '%env(ENQUEUE_DSN)%'

    ## App

    app.example.cqs:
        class: App\Example\QueryAndCommandProvider
        arguments:
            - '@Akeneo\Pim\ApiClient\AkeneoPimClient'

    App\Command\ImportCommand:
        arguments:
            - '@Aa\AkeneoImport\Import\Importer'
            -
                product: '@App\Example\ProductProvider'
                delete_product: '@App\Example\DeleteProvider'
                product_and_model: '@App\Example\ProductAndModelProvider'
                category: '@App\Example\CategoryProvider'
                media: '@App\Example\ProductWithMediaProvider'
                query: '@app.example.cqs'
                2level_model: '@App\Example\TwoLevelModelProvider'

        tags: ['console.command']

    App\Command\PublishCommand:
        arguments:
            - '@Aa\AkeneoImport\Queue\RemoteQueueFactory'
            -
                product: '@App\Example\ProductProvider'
                delete_product: '@App\Example\DeleteProvider'
                product_and_model: '@App\Example\ProductAndModelProvider'
                category: '@App\Example\CategoryProvider'
                media: '@App\Example\ProductWithMediaProvider'
                query: '@app.example.cqs'
        tags: ['console.command']

    App\Command\ConsumeCommand:
        arguments:
            - '@Aa\AkeneoImport\Queue\RemoteQueueFactory'
            - '@Aa\AkeneoImport\Import\Importer'
        tags: ['console.command']
