services:

    ### API batch handler

    Aa\AkeneoImport\CommandHandler\Api\ApiBatchHandler:
        factory: 'Aa\AkeneoImport\CommandHandler\Api\ApiBatchHandlerFactory:createHandler'

    Akeneo\Pim\ApiClient\AkeneoPimClientBuilder:
        arguments:
            - '%env(AKENEO_API_HOST)%'

    Akeneo\Pim\ApiClient\AkeneoPimClient:
        factory: 'Akeneo\Pim\ApiClient\AkeneoPimClientBuilder:buildAuthenticatedByPassword'
        arguments:
            - '%env(AKENEO_API_CLIENT_ID)%'
            - '%env(AKENEO_API_SECRET)%'
            - '%env(AKENEO_API_USER)%'
            - '%env(AKENEO_API_PASSWORD)%'

    Aa\AkeneoImport\CommandHandler\Api\ApiBatchHandlerFactory:
        arguments:
            - '@Akeneo\Pim\ApiClient\AkeneoPimClient'


    ## Akeneo Import

    Aa\AkeneoImport\CommandBus\Transport\TransportFactory:
        arguments:
          - '%env(ENQUEUE_DSN)%'

    Aa\AkeneoImport\CommandBus\Transport\Sender:
        factory: 'Aa\AkeneoImport\CommandBus\Transport\TransportFactory:createSender'

    Aa\AkeneoImport\CommandBus\Transport\Receiver:
        factory: 'Aa\AkeneoImport\CommandBus\Transport\TransportFactory:createReceiver'

    Aa\AkeneoImport\CommandHandler\Amqp\AsyncCommandBatchHandler:
        arguments:
          - '@Aa\AkeneoImport\CommandBus\Transport\Sender'

    Aa\AkeneoImport\CommandBus\CommandBusFactory:

    Aa\AkeneoImport\Import\Importer:
        arguments:
            - '@Aa\AkeneoImport\CommandBus\CommandBusFactory'

    Aa\AkeneoImport\CommandBus\Consumer:
        arguments:
            - '@Aa\AkeneoImport\CommandBus\Transport\Receiver'

    ## App

    App\Command\ImportCommand:
        arguments:
            - '@Aa\AkeneoImport\Import\Importer'
            -
                product: '@App\Example\TestProductProvider'
                product_and_model: '@App\Example\TestProductAndModelProvider'
                category: '@App\Example\CategoryProvider'
                media: '@App\Example\ProductWithMediaProvider'
                query: '@App\Example\QueryAndCommandProvider'
            -
                api: '@Aa\AkeneoImport\CommandHandler\Api\ApiBatchHandler'
                amqp: '@Aa\AkeneoImport\CommandHandler\Amqp\AsyncCommandBatchHandler'
        tags: ['console.command']

    App\Command\ConsumeCommand:
        arguments:
            - '@Aa\AkeneoImport\CommandBus\Consumer'
            -
                api: '@Aa\AkeneoImport\CommandHandler\Api\ApiBatchHandler'
            -
                product: 'Aa\AkeneoImport\ImportCommand\Product\UpdateOrCreateProduct'
                model: 'Aa\AkeneoImport\ImportCommand\ProductModel\UpdateOrCreateProductModel'
        tags: ['console.command']
