services:

    Akeneo\Pim\ApiClient\AkeneoPimClientBuilder:
        arguments:
            - '%env(AKENEO_API_HOST)%'

    Akeneo\Pim\ApiClient\AkeneoPimClient:
        factory: 'Akeneo\Pim\ApiClient\AkeneoPimClientBuilder:buildAuthenticatedByPassword'
        arguments:
            - '%env(AKENEO_API_CLIENT_ID)%'
            - '%env(AKENEO_API_SECRET)%'
            - '%env(AKENEO_API_USER)%'
            - '%env(AKENEO_API_PASSWORD)%'

    ### API command handler
    Aa\AkeneoImport\CommandHandler\Api\ApiCommandHandlerFactory:

    Aa\AkeneoImport\CommandHandler\Api\ApiCommandHandler:
        factory: 'Aa\AkeneoImport\CommandHandler\Api\ApiCommandHandlerFactory:createByApiClient'
        arguments:
            - '@Akeneo\Pim\ApiClient\AkeneoPimClient'

    ## Akeneo Import

    Aa\AkeneoImport\CommandHandler\Amqp\AmqpCommandHandlerFactory:

    Aa\AkeneoImport\CommandHandler\Amqp\AmqpCommandHandler:
        factory: 'Aa\AkeneoImport\CommandHandler\Amqp\AmqpCommandHandlerFactory:createByDsn'
        arguments:
          - '%env(ENQUEUE_DSN)%'

    Aa\AkeneoImport\Import\ImporterFactory:

    Aa\AkeneoImport\Import\Importer:
        factory: 'Aa\AkeneoImport\Import\ImporterFactory:create'

    Aa\AkeneoImport\Transport\ConsumerFactory:

    Aa\AkeneoImport\Transport\Consumer:
        factory: 'Aa\AkeneoImport\Transport\ConsumerFactory:createByDsn'
        arguments:
          - '%env(ENQUEUE_DSN)%'

    ## App

    app.example.cqs:
        class: App\Example\QueryAndCommandProvider
        arguments:
            - '@Akeneo\Pim\ApiClient\AkeneoPimClient'

    App\Command\ImportCommand:
        arguments:
            - '@Aa\AkeneoImport\Import\Importer'
            -
                product: '@App\Example\ProductProvider'
                delete_product: '@App\Example\DeleteProvider'
                product_and_model: '@App\Example\ProductAndModelProvider'
                category: '@App\Example\CategoryProvider'
                media: '@App\Example\ProductWithMediaProvider'
                query: '@app.example.cqs'
            -
                api: '@Aa\AkeneoImport\CommandHandler\Api\ApiCommandHandler'
                amqp: '@Aa\AkeneoImport\CommandHandler\Amqp\AmqpCommandHandler'
        tags: ['console.command']

    App\Command\ConsumeCommand:
        arguments:
            - '@Aa\AkeneoImport\Transport\Consumer'
            -
                api: '@Aa\AkeneoImport\CommandHandler\Api\ApiCommandHandler'
            -
                product: 'Aa\AkeneoImport\ImportCommand\Product\UpdateOrCreateProduct'
                model: 'Aa\AkeneoImport\ImportCommand\ProductModel\UpdateOrCreateProductModel'
        tags: ['console.command']
